$(document).ready(function(){
    $("#development-image").click(function(){
      $("#development-image").slideDown('1500').hide('1000');
      $("#development").show('2000');
    });
    $("#development").click(function(){
      $("#development").slideUp('2000');
      $("#development-image").slideDown('2000');
    });
  });
